name: Deploy API-WSP

on:
  push:
    branches:
      - main   # se ejecuta cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and Restart API-WSP
        run: |
          ssh -o StrictHostKeyChecking=no root@72.60.30.18 "
            cd /var/www/api-wsp && \
            git pull origin main && \
            pm2 restart api-ws || pm2 start ecosystem.config.js --name api-ws && \
            pm2 save
          "
